### ISSUE TITLE
function yubikey_reset_piv_applet() in ykneo_first_setup.sh fails

### ISSUE THREAD

**Issue by manoj23** [sbach/yubikey-tools#3]
All commands in the function yubikey_reset_piv_applet() in ykneo_first_setup.sh fail with the following error:

> Failed to connect to reader.

I tried to execute each commands independently unsuccessfully.

Is this function required to initialize the yubikey?

**Comment by manoj23** [comment]
I guess it is because my Yubikey NEO does not handle PIV applet. [1]

[1] https://forum.yubico.com/viewtopic.php?f=26&t=1965

**Comment by sbach** [comment]
This function was used with the Yubikey Neo given to you. You might be missing dependencies and/or one of the daemon have a lock on the key at the time.

**Comment by manoj23** [comment]
You are right, yubico-piv-tool requires pcscd.

The following line fixes the issue.
```
# systemctl enable pcscd
```
